### ISSUE TITLE
Re-thinking the cpak origins

### ISSUE THREAD

**Issue by mirkobrombin** [Containerpak/cpak#4]
Due to the new structure mentioned [here](https://github.com/Containerpak/cpak/issues/2), the `Version` field is being dropped so that developers does not have to handle it. Cpak will use the defined origin as the identifier (`origin:source`, where `origin` is the repo and `source` is a branch:commit or commit or release).

This involves both dependencies, future dependencies and exports. When a cpak defines another cpak as a dependency, this must also define the source from where it must be installed.

Before:

```json
{
  "name": "Visual Studio Code",
  "description": "Code editing. Redefined.",
  "version": "1.82.2",
  "image": "ghcr.io/containerpak/vscode:main",
  "binaries": [
    "/usr/share/code/bin/code"
  ],
  "desktop_entries": [
    "/usr/share/applications/code.desktop",
    "/usr/share/applications/code-url-handler.desktop"
  ],
  "dependencies": [ 
    "github.com/containerpak/git"
],
  "addons": [
    "github.com/containerpak/sdk-go",
    "github.com/containerpak/sdk-python"
  ],
...
```

and exports are structured this way:
- ~/.local/share/cpak/exports/github.com/containerpak/git/git

After:

```json
{
  "name": "Visual Studio Code",
  "description": "Code editing. Redefined.",
  "version": "1.82.2",
  "image": "ghcr.io/containerpak/vscode:main",
  "binaries": [
    "/usr/share/code/bin/code"
  ],
  "desktop_entries": [
    "/usr/share/applications/code.desktop",
    "/usr/share/applications/code-url-handler.desktop"
  ],
  "dependencies": [
    {
      "origin": "github.com/containerpak/git",
      "branch": "main"
    }
  ],
  "addons": [
    "github.com/containerpak/sdk-go",
    "github.com/containerpak/sdk-python"
  ],
...
```

and exports will be structured this way:
- ~/.local/share/cpak/exports/github.com/containerpak/git/branches/main/git

## Tasks
- [x] create Dependency struct
- [x] add dependencies field in the Application struct
- [x] store dependencies in store-db
- [x] adapt the export functions to export to the new paths
